<?php

/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace c975L\ConfigBundle\Tests\Management;

use c975L\ConfigBundle\Management\GuidedProjectBuilder;
use c975L\ConfigBundle\Management\GuidedProjectProviderInterface;
use PHPUnit\Framework\TestCase;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Contracts\Translation\TranslatorInterface;

class GuidedProjectBuilderTest extends TestCase
{
    private function createProvider(array $projects): GuidedProjectProviderInterface
    {
        $provider = $this->createStub(GuidedProjectProviderInterface::class);
        $provider->method('getGuidedProjects')->willReturn($projects);

        return $provider;
    }

    private function createTranslator(): TranslatorInterface
    {
        $translator = $this->createStub(TranslatorInterface::class);
        $translator->method('trans')->willReturnCallback(fn (string $id) => 'translated:' . $id);

        return $translator;
    }

    private function createSecurity(bool $isGranted = true): Security
    {
        $security = $this->createStub(Security::class);
        $security->method('isGranted')->willReturn($isGranted);

        return $security;
    }

    private function createBuilder(array $providers, bool $isGranted = true): GuidedProjectBuilder
    {
        return new GuidedProjectBuilder($providers, $this->createSecurity($isGranted), $this->createTranslator());
    }

    private function project(string $slug, int $order, array $extra = []): array
    {
        return array_merge([
            'slug' => $slug,
            'label' => 'label.' . $slug,
            'translation_domain' => 'site',
            'order' => $order,
            'steps' => [['label' => 'label.' . $slug . '_step']],
        ], $extra);
    }

    public function testGetProjectsTranslatesLabelsAndKeepsAnEmptyDescriptionEmpty(): void
    {
        $builder = $this->createBuilder([$this->createProvider([$this->project('creer-page', 10)])]);

        $this->assertSame(
            [[
                'slug' => 'creer-page',
                'label' => 'translated:label.creer-page',
                'description' => '',
                'steps' => [[
                    'label' => 'translated:label.creer-page_step',
                    'description' => '',
                    'narration' => 'translated:label.creer-page_step.',
                    'url' => null,
                    'highlight' => null,
                ]],
            ]],
            $builder->getProjects(),
        );
    }

    // "url" is generated by the contributing bundle and "highlight" is a CSS selector - neither goes through the translator
    public function testGetProjectsPassesUrlAndHighlightThroughUntranslated(): void
    {
        $builder = $this->createBuilder([$this->createProvider([
            $this->project('creer-page', 10, [
                'description' => 'description.creer-page',
                'steps' => [
                    ['label' => 'label.step_one', 'description' => 'description.step_one', 'url' => '/management/page'],
                    ['label' => 'label.step_two', 'highlight' => '.btn-new'],
                ],
            ]),
        ])]);

        $project = $builder->getProjects()[0];

        $this->assertSame('translated:description.creer-page', $project['description']);
        $this->assertSame('/management/page', $project['steps'][0]['url']);
        $this->assertNull($project['steps'][0]['highlight']);
        $this->assertSame('.btn-new', $project['steps'][1]['highlight']);
        $this->assertSame('translated:label.step_two', $project['steps'][1]['label']);
    }

    // What a step sounds like spoken, read by the films of the back office and by nothing on screen - and looked up in a domain of its own, the narrations being written in fewer locales than the rest of the bundle
    public function testGetProjectsTranslatesTheNarrationOfAStepInItsOwnDomain(): void
    {
        $translator = $this->createStub(TranslatorInterface::class);
        $translator->method('trans')->willReturnCallback(fn (string $id, array $parameters, string $domain) => $domain . ':' . $id);

        $builder = new GuidedProjectBuilder([$this->createProvider([
            $this->project('creer-page', 10, [
                'steps' => [['label' => 'label.step_one', 'narration' => 'narration.step_one']],
            ]),
        ])], $this->createSecurity(), $translator);

        $this->assertSame('site_narration:narration.step_one', $builder->getProjects()[0]['steps'][0]['narration']);
    }

    // A step nobody has written a sentence for is still said, its caption and its explanation read as one passage
    public function testAStepWithoutNarrationFallsBackToItsCaptionAndDescription(): void
    {
        $builder = $this->createBuilder([$this->createProvider([
            $this->project('creer-page', 10, [
                'steps' => [['label' => 'label.step_one', 'description' => 'description.step_one']],
            ]),
        ])]);

        $this->assertSame(
            'translated:label.step_one. translated:description.step_one',
            $builder->getProjects()[0]['steps'][0]['narration'],
        );
    }

    // "order" is a deliberate sequence across every provider (create a page, then add a block to it), not the alphabetical merge menus and alerts use
    public function testGetProjectsSortsEveryProviderTogetherByOrder(): void
    {
        $builder = $this->createBuilder([
            $this->createProvider([$this->project('creer-menu', 30), $this->project('creer-page', 10)]),
            $this->createProvider([$this->project('ajouter-bloc', 20)]),
        ]);

        $this->assertSame(
            ['creer-page', 'ajouter-bloc', 'creer-menu'],
            array_column($builder->getProjects(), 'slug'),
        );
    }

    public function testGetProjectsSkipsAProjectTheCurrentUserLacksTheRoleFor(): void
    {
        $builder = $this->createBuilder(
            [$this->createProvider([$this->project('gerer-utilisateur', 70, ['role' => 'ROLE_SUPER_ADMIN'])])],
            false,
        );

        $this->assertSame([], $builder->getProjects());
    }

    // The documentation of the back office reads every parcours, whatever role opens the screens it walks through - the reader's own role is checked again when they start one (see getProject())
    public function testGetAllProjectsKeepsAProjectTheCurrentUserLacksTheRoleFor(): void
    {
        $builder = $this->createBuilder(
            [$this->createProvider([$this->project('gerer-utilisateur', 70, ['role' => 'ROLE_SUPER_ADMIN'])])],
            false,
        );

        $this->assertSame([], $builder->getProjects());
        $this->assertSame(['gerer-utilisateur'], array_column($builder->getAllProjects(), 'slug'));
    }

    public function testGetProjectsKeepsAProjectWithoutARole(): void
    {
        $builder = $this->createBuilder([$this->createProvider([$this->project('creer-page', 10)])], false);

        $this->assertCount(1, $builder->getProjects());
    }

    public function testGetProjectReturnsTheMatchingProject(): void
    {
        $builder = $this->createBuilder([$this->createProvider([
            $this->project('creer-page', 10),
            $this->project('creer-menu', 20),
        ])]);

        $this->assertSame('creer-menu', $builder->getProject('creer-menu')['slug']);
    }

    // The slug comes from the browser's own storage and is the user's to forge, so both an unknown one and one they lack the role for have to come back empty-handed
    public function testGetProjectReturnsNullForAnUnknownSlug(): void
    {
        $builder = $this->createBuilder([$this->createProvider([$this->project('creer-page', 10)])]);

        $this->assertNull($builder->getProject('gone-with-its-bundle'));
    }

    public function testGetProjectReturnsNullForAProjectTheCurrentUserLacksTheRoleFor(): void
    {
        $builder = $this->createBuilder(
            [$this->createProvider([$this->project('gerer-utilisateur', 70, ['role' => 'ROLE_SUPER_ADMIN'])])],
            false,
        );

        $this->assertNull($builder->getProject('gerer-utilisateur'));
    }

    public function testGetProjectsReturnsNothingWithoutAnyProvider(): void
    {
        $this->assertSame([], $this->createBuilder([])->getProjects());
    }
}
