<?php

/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace c975L\ConfigBundle\Tests\Service;

use c975L\ConfigBundle\Entity\NotFound;
use c975L\ConfigBundle\Entity\Redirect;
use c975L\ConfigBundle\Service\ConfigDemoFixtureProvider;
use PHPUnit\Framework\TestCase;

// What a demo site is asked for and does not serve - the only rows of this bundle a dataset writes, everything else it lists being generated by a command
class ConfigDemoFixtureProviderTest extends TestCase
{
    /** @return list<object> */
    private function fixtures(): array
    {
        return iterator_to_array(new ConfigDemoFixtureProvider()->getDemoFixtures(), false);
    }

    public function testItSeedsThreeMissingAddressesAndOneRedirection(): void
    {
        $fixtures = $this->fixtures();

        $this->assertCount(4, $fixtures);
        $this->assertContainsOnlyInstancesOf(NotFound::class, \array_slice($fixtures, 0, 3));
        $this->assertInstanceOf(Redirect::class, $fixtures[3]);
    }

    // The one case that is a bug rather than a fact: the site links to an address it does not serve
    public function testExactlyOneOfThemComesFromTheSiteItself(): void
    {
        $internal = array_filter($this->fixtures(), static fn (object $row) => $row instanceof NotFound && $row->isInternal());

        $this->assertCount(1, $internal);
        $this->assertSame('/documentation/pdf', reset($internal)->getPath());
    }

    // A demo is reloaded often, and a date taken from the clock would have the screen say something else in every take of the same recorded sequence
    public function testTheDatesAreFixedRatherThanTakenFromTheClock(): void
    {
        foreach ($this->fixtures() as $row) {
            if (!$row instanceof NotFound) {
                continue;
            }

            $this->assertSame('2026-02-11', $row->getFirstSeen()->format('Y-m-d'));
            $this->assertSame('2026-02-24', $row->getLastSeen()->format('Y-m-d'));
        }
    }

    // A redirection nobody can follow is worse than none: the screen would show a rule pointing at an address the site does not serve either
    public function testTheRedirectionPointsAtAnAddressAndIsPermanent(): void
    {
        $redirect = $this->fixtures()[3];

        $this->assertSame('/anciennes-realisations', $redirect->getFromPath());
        $this->assertSame('/realisations', $redirect->getToUrl());
        $this->assertTrue($redirect->isPermanent());
        $this->assertFalse($redirect->isGone());
    }
}
