<?php

/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace c975L\UiBundle\Command;

use c975L\UiBundle\Registry\EmailTemplateProviderRegistry;
use c975L\UiBundle\Repository\EmailTemplateRepository;
use c975L\UiBundle\Service\FormSeeder;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

// Seeds the e-mail every installed bundle says a site should be able to send, and only the ones it cannot yet. Safe on every deployment: a template already there, composed or emptied by an admin, is never touched
#[AsCommand(
    name: 'c975l:ui:email-templates:ensure',
    description: 'Creates the email templates the installed bundles declare and the site does not have yet',
)]
class EmailTemplateEnsureCommand extends Command
{
    public function __construct(
        private readonly EmailTemplateProviderRegistry $emailTemplateProviderRegistry,
        private readonly EmailTemplateRepository $emailTemplateRepository,
        private readonly EntityManagerInterface $entityManager,
        private readonly FormSeeder $formSeeder,
        #[Autowire(param: 'kernel.default_locale')]
        private readonly string $defaultLocale = 'en',
    ) {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $adopted = $this->adoptLocalelessRows($io);

        $before = $this->emailTemplateRepository->count([]);

        $backfilled = 0;
        foreach ($this->emailTemplateProviderRegistry->getDeclaredTemplates() as $name => $blocksByLocale) {
            $backfilled += $this->formSeeder->ensureEmailTemplate($name, $blocksByLocale);
        }

        $this->entityManager->flush();

        $created = $this->emailTemplateRepository->count([]) - $before;

        // Named rather than counted: a template appearing on a site is content its admin will find in the back-office without having asked for it
        if ($created > 0) {
            $io->listing(array_map(
                static fn (object $emailTemplate): string => (string) $emailTemplate,
                $this->emailTemplateRepository->findBy([], ['name' => 'ASC', 'locale' => 'ASC'])
            ));
        }

        // Said rather than left silent: a block appearing in an e-mail a site already sends is something its admin should read here first
        if ($backfilled > 0) {
            $io->text(sprintf('%d block(s) declared since those templates were seeded were added at their end.', $backfilled));
        }

        $io->success(sprintf('%d email template(s) created, %d adopted, %d block(s) backfilled.', $created, $adopted, $backfilled));

        return Command::SUCCESS;
    }

    /**
     * Gives the site's own language to the rows that predate EmailTemplate having a language at all.
     *
     * A template used to be one row, unique on its name. The column that says which language it is written in
     * arrives through a Doctrine migration, and a migration generated by doctrine:migrations:diff carries the
     * ALTER and nothing else - it compares schemas, it knows nothing about rows. So every template a site had
     * lands with an empty locale.
     *
     * Left that way, seeding no longer recognises them: it looks for (name, "fr"), finds nothing, and writes a
     * second "password_reset" beside the first. The admin then edits one of the two and the other is the one
     * being sent. Adopting them here rather than asking fifteen migrations to be hand-edited, because a manual
     * step repeated fifteen times is a manual step forgotten once.
     *
     * Skips a row whose language already has its own version: two rows for one name and one language cannot both
     * exist, and of the two the one that is already right is not the one to touch. The health check reports what
     * is left over.
     */
    private function adoptLocalelessRows(SymfonyStyle $io): int
    {
        $adopted = 0;
        foreach ($this->emailTemplateRepository->findBy(['locale' => '']) as $emailTemplate) {
            if (null !== $this->emailTemplateRepository->findOneBy(['name' => $emailTemplate->getName(), 'locale' => $this->defaultLocale])) {
                $io->warning(sprintf('"%s" has both a version with no language and one in %s: left as it is, since only one of the two can keep that name.', (string) $emailTemplate->getName(), $this->defaultLocale));

                continue;
            }

            $emailTemplate->setLocale($this->defaultLocale);
            ++$adopted;
        }

        if ($adopted > 0) {
            $this->entityManager->flush();
            $io->text(sprintf('%d template(s) written before e-mails had a language are now the %s ones.', $adopted, $this->defaultLocale));
        }

        return $adopted;
    }
}
