<?php

/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace c975L\UiBundle\Service;

use c975L\UiBundle\Contract\BundleStylesheetManagementProviderInterface;
use c975L\UiBundle\Contract\BundleStylesheetProviderInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

class StylesheetProvider implements BundleStylesheetProviderInterface, BundleStylesheetManagementProviderInterface
{
    public function __construct(
        #[Autowire(param: 'c975l_ui.build_dir')]
        private readonly string $buildDir,
    ) {
    }

    public function getStylesheets(): array
    {
        return [
            'bundles/c975lui/css/animations.min.css',
            'bundles/c975lui/css/styles.min.css',
            // Generated by FontCssListener from every admin-uploaded Font row (see FontCrudController) - order doesn't matter, @font-face rules don't participate in the cascade
            $this->buildDir . '/site-fonts-uploaded.css',
        ];
    }

    public function getManagementStylesheets(): array
    {
        return [
            'bundles/c975lui/css/management.min.css',
        ];
    }
}
