<?php

/*
 * (c) 2026: 975L <contact@975l.com>
 * (c) 2026: Laurent Marquet <laurent.marquet@laposte.net>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace c975L\UiBundle\Service;

use c975L\UiBundle\Contract\BundleStylesheetProviderInterface;

// A provider of its own rather than one more entry in StylesheetProvider, because its position in the cascade is the whole point: the file holds the admin's own theme values as ":root" custom properties, so it has to load after every bundle's compiled defaults (all tagged at priority 100) and before the app's theme files (auto-tagged at -100, where "uncommenting a token takes it back from the bundle" only works if the app still wins)
class ThemeVariablesStylesheetProvider implements BundleStylesheetProviderInterface
{
    public function getStylesheets(): array
    {
        return [
            // Generated by ThemeVariablesCssListener from the admin-editable "theme" group configs
            'bundles/build/site-theme.css',
        ];
    }
}
